// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PriceAggregator.Api.Data;

#nullable disable

namespace PriceAggregator.Api.Migrations
{
    [DbContext(typeof(PriceAggregatorApiContext))]
    partial class PriceAggregatorApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PriceAggregator.Api.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Close")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("close");

                    b.Property<string>("High")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("high");

                    b.Property<string>("Low")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("low");

                    b.Property<string>("Open")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("open");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timestamp");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.ToTable("prices");
                });
#pragma warning restore 612, 618
        }
    }
}
